config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root 'home#index'


   namespace :admin do
    root 'home#index'
    resources :users
    resources :posts
    end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
	has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  STATUSES = {
    admin: 'admin',
    editor: 'editor',
    user: 'user'
  }
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.status != 'admin' && current_user.status != 'editor'
      redirect_to root_path
      
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	before_action :authenticate_user!

	before_action :find_post, only: %i[ show edit update destroy ]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end



	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to admin_post_path(@post)
		else
			redirect_to admin_post_path
	end
	end

	def show
		
	end


	
	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :body, :image)
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :authenticate_user!

	def index
		
		if current_user.status == 'admin' || current_user.status == 'editor'
			@users = User.all
		else
			redirect_to root_path
			
		end
	end


	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to admin_users_path
	end

	private

	
	def user_params
		params.require(:user).permit(:status)
		
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController


	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:status])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/home/index.html.erb
<h1>Admin::Home#index</h1>
<p>Find me in app/views/admin/home/index.html.erb</p>

app/views/admin/posts/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 mx-auto">
			<%= form_for [:admin, @post] do |f| %>

				<div class="form-group">
					<%= f.label :title %>
					<%= f.text_field :title, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label :body %>
					<%= f.text_area :body, class: 'form-control', rows: 10 %>
				</div>
				<div class="form-group">
					<%= f.label :image %>
					<%= f.file_field :image, class: 'form-control', rows: 10 %>
				</div>
				<div class="form-group">
					<%= f.submit class: 'btn btn-success' %>
					
				</div>

			<% end %>
		</div>
	</div>
</div>

app/views/admin/posts/index.html.erb
<%= link_to 'New', new_admin_post_path %>
<% @posts.each do |post| %>
	<h1><%= link_to post.title, admin_post_path(post) %></h1>
	<h1><%= link_to post.body, admin_post_path(post) %></h1>
	
<% end %>

app/views/admin/posts/new.html.erb
<h2 class="text-center">NEW POST</h2>


<%= render 'form' %>

app/views/admin/posts/show.html.erb
<h1><%= @post.title %></h1>

<h4><%= @post.body %></h4>

<%= image_tag @post.image %>

app/views/admin/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', admin_users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Main', root_path, class: 'btn btn-primary nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<%= form_for [:admin, @user] do |f| %>
			<%= f.select :status, options_for_select(User:: 
			STATUSES,{class: 'form-select'}) %>
			<div class="form-group">
				<%= f.submit class: 'btn btn-primary' %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col"></div>
		<h1 >USERS</h1>
	</div>

	<div class="row">
		<div class="col">
			<table class="table table-border table-striped">
				<thead>
					<th>USERNAME</th>
					<th>EMAIL</th>
					<th>STATUS</th>
					<th>PROFILE</th>
					<th>EDIT</th>
					
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td>username</td>
						<td><%= user.email %></td>
						<td><%= user.status %></td>
						<td><%= link_to 'Profile', admin_user_path(user), class: 'btn btn-info' %></td>
						<td><%= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-warning' %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Latestruby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if controller_path =~/^admin\// %>
    <%= render 'admin/shared/header' %>
    <% else %>
    <%= render 'shared/header' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
        <% if current_user %>
          <%= button_to 'LogOut', destroy_user_session_path, method: :delete, class: 'btn btn-outline-success' %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-success' %>
        <% end %>

        <% if  current_user && (current_user.status == 'admin' || current_user.status == 'editor') %>
        <%= link_to 'Admin', admin_root_path, class: 'btn btn-dark' %>
        <% end %>

    </div>
  </div>
</nav>